LETS MASTER THE TERRAFORM FROM BASICS TO ADVANCED AND CRACK THE CERTIFICATION 
I HAVE USED THE FOLLOWING ORDER TO LEARN 
1.TERRAFORM BASIS -> CREATING AND DEPLOYING IAC
2.TERRAFORM LANGUAGE := LEARN HOW TO USE BASIC COMMANDS ,BLOCKS,VALIDATIONS,FORMATING AND MANY MORE
3.HOW TO MAKE USE OF COMMANDS TO RUN WITH TERRAFORM:
   - PROVISONERS
   -USE OF VARIOUS PROVISONER
    - FAILURE BEHAIVIOUR OF THE PROVISIONERS
4.MODULING AND MANAGING WORKSPACES :
  - HOW TO CREATE WORKSPAECES
 - HOW TO CONVERT OUR CODE INTO A MODULE
  - LEVERAGING THE USAGE OF VARIABLES ACROSS THE MODULES
 5. REMOTE STATE MANAGEMENT :
  INTEGRATING GIT FOR OUR WORKSPACE ACROSS THE TEAMS
   - LOCKING OUR STATE WITH S3
   - SECURITY ASPECTS IN STATE FILE LOCKING
    - HOW TO MAKE SURE OF OUR PASSWORDS AND ACESS KEYS IN A SECURE WAY 
  6. ENTERPRISE FLAVOUR OF TERRAFORM AND ITS PROS 
  7. IMPORTANT TOPICS TO SEE FOR THE CERTIFCATION 
  
 
